{% set version = "0.3.1" %}

package:
  name: climlab-cam3-radiation
  version: {{ version }}

source:
  url: https://github.com/climlab/climlab-cam3-radiation/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 39971c0c092e90e9ab424ba2e1ec6975d5db88e881ff3d9fedd5244b6a51f071

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja
    - pkg-config
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - meson-python
    - python
    - python-build
    - pip
    - numpy
    - packaging >=20.0
  run:
    - python
    - numpy
    - xarray
    - pooch
    - netcdf4

test:
  requires:
    - pytest
  imports:
    - climlab_cam3_radiation
  commands:
    - pytest -v --pyargs climlab_cam3_radiation

about:
  home: https://github.com/climlab/climlab-cam3-radiation
  summary: 'Standalone Python wrapper for the NCAR CAM3 radiation scheme'
  description: |
    climlab-cam3-radiation makes the CAM3 radiation code callable
    from Python by wrapping using f2py. This is a lightweight wrapper that
    emulates the Fortran interface as closely as possible. The primary use case
    is to drive the radiation process in climlab, but it can be used as
    a standalone driver if you are familiar with the Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-cam3-radiation

extra:
  recipe-maintainers:
    - brian-rose
